### ISSUE TITLE
详细解说

### ISSUE THREAD

**Issue by DengCaiYun** [luca-morreale/indoor-localization#1]
能给点详细解说吗？最近正研究这个，小白一个，看不懂呢

**Comment by luca-morreale** [comment]
I will update the README file in the next few days, if it will not be enough please ask.

**Comment by DengCaiYun** [comment]
灰常感谢，我最近正在研究Wifi室内定位的项目，想用Matlab做仿真实验，不知如何下手呢，要是能对Matlab module作更详细的解释就好啦，哈哈

------------------ 原始邮件 ------------------
发件人: "Luca Morreale";notifications@github.com;
发送时间: 2016年11月1日(星期二) 凌晨3:23
收件人: "luca-morreale/indoor-localization"indoor-localization@noreply.github.com; 
抄送: "凌沧海"1345772438@qq.com; "Author"author@noreply.github.com; 
主题: Re: [luca-morreale/indoor-localization] 详细解说 (#1)

I will update the README file in the next few days, if it will not be enough please ask.
